### ISSUE TITLE
Doesn't work with development build

### ISSUE THREAD

**Issue by MnogoZnaet** [Syn-McJ/TFClassify-Unity#1]
Hi! Man you did a great job, thank you! I was trying to build it with development build option turned on, but it doesn't work.

**Comment by Syn-McJ** [comment]
Hi, yes, seems like GetPixels() method has problems with executing in background thread, but only in dev build for some reason. I moved call to main thread, please check it again.

**Comment by MnogoZnaet** [comment]
Can't check right now. I don't know what exactly happend but suddenly tensorflow stoped working, giving me "Unable to find libtensorflow" error on android device. The problem appeared yesterday even before latest commit when i was trying to switch back from development build. Maybe you have any ideas?

**Comment by Syn-McJ** [comment]
No, not sure about that one. Reinstall tensorflow plugin maybe?

**Comment by Syn-McJ** [comment]
I'm gonna close this issue as fixed, feel free to reopen if there are still issues with development build.
