### ISSUE TITLE
The name `TensorFlowSharp' does not exist in the current context

### ISSUE THREAD

**Issue by saikatbsk** [Syn-McJ/TFClassify-Unity#14]
Hi, the project builds on Mac but when I am changing build platform to Android I am getting the following error:

Assets/Scripts/Classifier.cs(26,13): error CS0103: The name `TensorFlowSharp' does not exist in the current context

Any idea why is it happening?

Thanks in advanced.

**Comment by Syn-McJ** [comment]
Hi, this error indicates problem with your TensorFlow plugin for Unity installation. You should check that, maybe try to recreate project and install it again.

**Comment by saikatbsk** [comment]
Thanks for the quick responce.
