### ISSUE TITLE
Is there a way to modify the label.txt file?

### ISSUE THREAD

**Issue by mking1011** [Syn-McJ/TFClassify-Unity#15]
Is there a way to modify the label.txt file?

I just changed the label.txt using editplus.

Is there a problem with my method?

**Comment by Burgomehl** [comment]
Of course you can change a txt file like this, but what do you think will be the result of it?

**Comment by mking1011** [comment]
@Burgomehl 
The results were not good.
Can you tell me another good way?

**Comment by Burgomehl** [comment]
Just changing the label.txt file will not show you some new detected objects. You need to train the model you are using.

Or what do you expect it to do?

**Comment by mking1011** [comment]
@Burgomehl 
Ah! I made the question strange. I have a newly trained model.
 I would like to have the appropriate label.txt

**Comment by Burgomehl** [comment]
(From the Readme)
To use your own model: 

Make sure your model trained with TensorFlow 1.4 if you use 0.3 version of the Unity plugin that I linked above. You can also try 0.4 version that uses TensorFlow 1.7.1.
Change extension of your model from .pb to .bytes.
Put your model and labels in Resources.
Set Model file and Labels file to your model and labels in main camera object of the scene you chose.
If neccesary, change classifyImageSize, IMAGE_MEAN, IMAGE_STD, INPUT_NAME and OUTPUT_NAME to suit your model.

Why was the Result not good?

**Comment by mking1011** [comment]
@Burgomehl 
I trained two classes. But only one class is well aware

**Comment by Burgomehl** [comment]
I think it's all about four fist and palm object detection? (https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/issues/148)
How did you train? 
How many images?
What does your config file look like?

**Comment by mking1011** [comment]
@Burgomehl 
Here are the files I trained
(EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#148)

I trained with 16000 fist photos and 16000 palm images

**Comment by Burgomehl** [comment]
You found a solution? @mking1011

**Comment by mking1011** [comment]
@Burgomehl 
I increased the number of pictures with fists and palm.
That solved the problem.
