### ISSUE TITLE
Procedure for Tensorflow 1.8 & 1.9

### ISSUE THREAD

**Issue by BernardinD** [Syn-McJ/TFClassify-Unity#18]
Does changing the extension on the pb graph file not work for Tensorflow version about 1.7? And for that matter, does the plugin work for these version?
I'm trying to run the plugin on a graph made from Tensorflow 1.9. I've tried just changing the extension but that just causes the program to crash from the start. I've also tried converting it using [ml-agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md)'s script but that isn't working for me right now either so I'm hoping this will give me more luck

Thx in advance

**Comment by Syn-McJ** [comment]
Hi @BernardinD,
I'm sorry for such a late response.

Unity TensorFlow plugin version 0.4 does indeed using TensorFlow version 1.7.1 and most probably won't work with versions above that. From [Unity ml-agents page](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md) I can see that plugin version 0.5 is out already, but judging by [requirements](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/requirements.txt) it still uses 1.7.1, so it seems you'll have to train your model with that version of TensorFlow.

**Comment by BernardinD** [comment]
Hi @Syn-McJ,
I'm sorry as well. I found a way around it but forgot to respond as such. 

I simply had to freeze the graph using 1.7. No need to retrain, just needed another PC or environment to run the previous version (tensorflow library & models repo) with my checkpoints to receive the graph. And with that graph I had no issues changing the extension

**Comment by BernardinD** [comment]
> Hi @Syn-McJ,
> I'm sorry as well. I found a way around it but forgot to respond as such.
> 
> I simply had to freeze the graph using 1.7. No need to retrain, just needed another PC or environment to run the previous version (tensorflow library & models repo) with my checkpoints to receive the graph. And with that graph I had no issues changing the extension
