### ISSUE TITLE
Getting Error when test on iOS

### ISSUE THREAD

**Issue by RaymondZxL** [Syn-McJ/TFClassify-Unity#19]
So I got errors while testing the app on iOS

iOS version: 12.1
Unity version: 2018.2.15f1

Error: F tensorflow/core/graph/graph.cc:238] Non-OK-status: status status: Not found: Op type not registered 'NoOp'

Is it version problem with iOS?

**Comment by Syn-McJ** [comment]
Hi @RaymondZxL,
I haven't tested this example on iOS unfortunately, so I'm not sure what the problem could be. Maybe sometime in future I'll get a iOS device and check it.

**Comment by RaymondZxL** [comment]
@Syn-McJ 
Okay, I will try figure it out. It seems like it's the TFsharp getting value 'NoOp' during constructing the TFGraph, and for some reason 'NoOp' is not one of the option.

Thanks anyway!

**Comment by Syn-McJ** [comment]
Hi @RaymondZxL,
I know it's super late, but I just managed to get a hold of ios device and a mac and tested the sample. I did encounter your problem, but it seems to be fixable with next steps in Xcode:

> In Build Settings > Linking > Other Linker Flags:
Double click on the flag list to expand the list
Add -force_load
Drag the library libtensorflow-core.a from the Project Navigator on the left under Libraries/ML-Agents/Plugins/iOS into the flag list, after -force_load.

Solution found [here](https://github.com/infocom-tpo/PoseNet-Unity/issues/1#issuecomment-409785835) and more info [here](https://github.com/llSourcell/Unity_ML_Agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity-(Experimental).md#ios-additional-instructions-for-building).
