### ISSUE TITLE
Recreating the graph every time you classify/detect an image causes unnecessary load

### ISSUE THREAD

**Issue by johnfriedrich** [Syn-McJ/TFClassify-Unity#21]
Hey,

I am playing around with this project a lot and when looking into these performance issues, I realized that you are recreating the graph session every time you classify/detect an image.

You can simply cache the session as global variable. This doubles or even tripples fps, depending on the graph size.

But I have no idea with it causes problems if you use the same session for multiple classifiies/detections, but ti shouldn't

**Comment by Syn-McJ** [comment]
Hi @i9hdkill,

Thanks for the hint! I tried to store session in a global variable, but haven't noticed any difference. Could you tell how you measured performance gains?

**Comment by Syn-McJ** [comment]
Hi @i9hdkill,

Since I haven't noticed performance improvements when saving the session in a global variable and the graph isn't actually getting recreated each time, it's unclear how you managed to increase fps. I'll close this issue, but feel free to reopen if you have more comments.
