### ISSUE TITLE
Need the PhoneCamera Configuration items

### ISSUE THREAD

**Issue by frajos100** [Syn-McJ/TFClassify-Unity#23]
Need the PhoneCamera Configuration items like BackGround etc.
Error coming up at line 55
NullReferenceException: Object reference not set to an instance of an object
PhoneCamera.Start () (at Assets/Scripts/PhoneCamera.cs:55)

**Comment by Syn-McJ** [comment]
Hi @frajos100,
I don't quite get what is the problem that you have. Can you explain in more detail?

**Comment by frajos100** [comment]
On opening the project and selecting Main Camera. In the Inspector no Component has been assigned as a result i click on Add Component and select Phone Camera from the list. The Script gets loaded and needs some parameters like BackGround, Filter, Model File and Labels File. For Model File and Labels file can be linked to items in Resource folder but not Background or Filter. Could you guide me as to what values needs to be selected?

**Comment by frajos100** [comment]
On opening the project and selecting Main Camera. In the Inspector no Component has been assigned as a result i click on Add Component and select Phone Camera from the list. The Script gets loaded and needs some parameters like BackGround, Filter, Model File and Labels File. The Model File and Labels file can be linked to items in Resource folder but cannot find any for Background or Filter. Could you guide me as to what values needs to be selected?

**Comment by Syn-McJ** [comment]
Hi @frajos100,
The sample should work without changing anything, I recommend you to clone it and try again. I will recheck later today if there are any errors I didn't notice.

**Comment by Syn-McJ** [comment]
Hi @frajos100,
Sorry for late response. I rechecked the sample and indeed, it works without any changes. You probably made some accidental changes to the project when opening it. Resetting branch or cloning from scratch should fix it.
