### ISSUE TITLE
performance not same as in python

### ISSUE THREAD

**Issue by Amanpradhan** [Syn-McJ/TFClassify-Unity#24]
Hello, I trained a custom mobilenet ssd object detector model, which works just fine in python but the performance is very poor in unity. What do I need to do in order to improve its performance?+

**Comment by Syn-McJ** [comment]
Hi @Amanpradhan,
I'm not quite sure. If you check the readme you'll see I made a note about this.
Feel free to leave any suggestions.

**Comment by Amanpradhan** [comment]
When I am showing 3 objects in a frame, it is making 3 bounding boxes, just not at the right coordinates. Do you have any idea why?

**Comment by Syn-McJ** [comment]
Hi @Amanpradhan,
If your model produces correct borders in python, then it's most likely a misalignment in unity. You can check if the camera background is positioned correctly, maybe try to save a raw picture with border coordinates and see what kind of shift occurs, then fix it manually.

As I mentioned in the readme, I'm no Unity expert, and this repo only meant as an example. However when I checked object detection, even though performance was poor, borders around objects were somewhat accurate. So I'm not sure what can be the problem in your case.

**Comment by Syn-McJ** [comment]
Hi @Amanpradhan,
If you're using newer versions of Unity, your problem might be related to https://github.com/Syn-McJ/TFClassify-Unity/issues/25
I'll close this issue.
