### ISSUE TITLE
Unable to find back camera

### ISSUE THREAD

**Issue by YMadane** [Syn-McJ/TFClassify-Unity#26]
The project is building but getting this error. My PC has a back camera as well

![image](https://user-images.githubusercontent.com/43282301/55188613-d5afe080-5169-11e9-8a37-fb1748be80e5.png)

**Comment by yxzhan** [comment]
There is a logic in Scripts/PhoneCamera.cs line 68 that only use back camera only, if you're running on laptop. you can just comment it out.

```CSharp        
 // if(!devices[i].isFrontFacing)
 // {
              this.backCamera = new WebCamTexture(devices[i].name, Screen.width, Screen.height);
 // }
```
