### ISSUE TITLE
Unloading broken assembly Assets/ML-Agents/Plugins/Android/TensorFlowSharp.Android.dll, this assembly can cause crashes in the runtime

### ISSUE THREAD

**Issue by aaronvdbrugge** [Syn-McJ/TFClassify-Unity#27]
First thing when opening the TensorFlow Unity Package, I get this error:

Unloading broken assembly Assets/ML-Agents/Plugins/Android/TensorFlowSharp.Android.dll, this assembly can cause crashes in the runtime

**Comment by Syn-McJ** [comment]
@aaronvdbrugge this error shouldn't affect functionality of the sample. I don't know why it shows this error, perhaps you should open an issue in https://github.com/Unity-Technologies/ml-agents
