### ISSUE TITLE
Errors on iOS

### ISSUE THREAD

**Issue by iAmNaz** [Syn-McJ/TFClassify-Unity#29]
I built and ran the project for iOS 12/iPhone 7 and I am getting the error below:

TFException: No OpKernel was registered to support Op 'Less' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_FLOAT]

Any idea how to address this issue? Thanks

**Comment by Syn-McJ** [comment]
Are you trying your own model or the one that comes with the sample?

**Comment by iAmNaz** [comment]
I only used what I checked out here.

<img width="471" alt="Screen Shot 2019-08-28 at 6 03 27 PM" src="https://user-images.githubusercontent.com/9004747/63846399-4e87c280-c9be-11e9-8dab-ec68ae3918d5.png">

**Comment by Syn-McJ** [comment]
Unfortunately, my iOS device is busted and I can't check this right now. But the error you're getting means the model has certain operation (in this case 'Less') that isn't supported. You might want to try to strip this operation from the graph or train another model that doesn't use it in the first place.

**Comment by Syn-McJ** [comment]
You might want to check my new example that uses new Unity Barracuda inference engine instead of TensorFlow Sharp, it works much better with iOS: https://github.com/Syn-McJ/TFClassify-Unity-Barracuda
