### ISSUE TITLE
How do I implement Tensorflow objection detection api in Unity?

### ISSUE THREAD

**Issue by tomtomtong** [Syn-McJ/TFClassify-Unity#3]
https://github.com/tensorflow/models/tree/master/research/object_detection

Thx for any advice.

**Comment by Syn-McJ** [comment]
I haven't looked into object detection yet, but I expect it shouldn't be too difficult. I will get back to you and maybe add an example as soon as I have anything.

**Comment by alexwzk** [comment]
Amazing! @Syn-McJ, working on object detection too! Looking forward to your updates! Thanks in advance!

**Comment by sabariprasad** [comment]
Any update on this????

**Comment by Syn-McJ** [comment]
Hi, no, unfortunately I haven't had time to look into this yet.

**Comment by Syn-McJ** [comment]
Hey guys, I've managed to hack together an example of object detection. Although it works, performance isn't great comparing to Android sample from TensorFlow repo. If you want to test your own model, process should be the same - rename extension from .pb to .bytes and replace model file and labels in the scene with your own. Check Readme for more info.

Feel free to open an issue if anything is unclear.
