### ISSUE TITLE
Issue with tiny-yolov2 graph

### ISSUE THREAD

**Issue by alpertungakin** [Syn-McJ/TFClassify-Unity#30]
Hello,
I was trying to use your project with tiny-yolov2 graph and coco labels. I trained the graph with tensorflow-gpu 1.4.0. I've not seen any error message but it cannot detect any object with Android phone. There wasnt any problem with other graphs. Here is the screenshot of inspector
![Ekran Alıntısı](https://user-images.githubusercontent.com/49777063/66719925-c3904980-edfe-11e9-8160-1ec37ef1a193.PNG)

**Comment by Syn-McJ** [comment]
I'm not ML expert, but I take it that tiny-yolov2 has different architecture from mobilenet ssd, so it's expected that it's not gonna work. I imagine that for your model you'll have to modify DetectAsync methon in Detector.cs, figure out inputs/outputs and how to get boxes correctly.

**Comment by alpertungakin** [comment]
Thank you. I will try and write the result here.

**Comment by Syn-McJ** [comment]
For YOLO model, you might want to check my new example: https://github.com/Syn-McJ/TFClassify-Unity-Barracuda
