### ISSUE TITLE
Boxes aren't drawn in Detect scene

### ISSUE THREAD

**Issue by AnaRhisT94** [Syn-McJ/TFClassify-Unity#31]
Hi Andrey, ( @Syn-McJ )

When I'm using `Detect` scene on my Android device, it doesn't drawn any rectangles on the screen.

However, with play button and using another camera, it sometimes draws the rectangle on the whole screen, but very not accurate. (I don't need it to work on the editor anyways)

Any ideas why this happens? I see in your README file that you did get the boxes drawn.

**Comment by AnaRhisT94** [comment]
I always used `Build & Run settings` when first time I added the `Classify` scene. How I found it out?
I went to `Build settings` and I noticed that it was building the `Classify` scene all the time. Changed it to `Detect` and problem solved. 

Btw, the boxes that are drawn are mostly on the whole screen.
Also, the detection is very slow, it takes a couple of seconds and detects just one thing.
Any ideas how to solve it?
What phone did you use? Maybe it about settings problem?

**Comment by Syn-McJ** [comment]
Hi @AnaRhisT94,

I see the problem with boxes, it relates to changes that happened in Unity which made camera texture have different size. I'll check how to fix this.

As for detection being slow, I mentioned this in readme and I still don't know how to improve this. Unity released their own inference library called [Barracuda](https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/Barracuda.md) to replace TensorFlow Sharp, however last time I tried it I couldn't make it work with my model, but perhaps you'll have better luck.

**Comment by Syn-McJ** [comment]
I'm going to close this issue, feel free to reopen if the problem persists. 
You can also check my [new Barracuda example](https://github.com/Syn-McJ/TFClassify-Unity-Barracuda), it should have better performace, but only supports YOLO for now.
