### ISSUE TITLE
Detect mode is not able to identify chair but the Coco labels has chair as labels

### ISSUE THREAD

**Issue by chahatagarwal** [Syn-McJ/TFClassify-Unity#33]
I wanted to know that, whether you had trained your own model ? And made as .byte file? If I change the model file. It throws an error. Would like to know how the detector script is working?

**Comment by codemaker2015** [comment]
> I wanted to know that, whether you had trained your own model ? And made as .byte file? If I change the model file. It throws an error. Would like to know how the detector script is working?

I am also facing the same issue. If you could help that would be great

**Comment by Syn-McJ** [comment]
Hi,
I didn't try it with my own detect model, only classifier, but I expect there shouldn't be a problem if you train another ssd-mobilenet model. What is your model's architecture? And what error are you getting?

**Comment by Syn-McJ** [comment]
I'm going to close this issue, feel free to reopen if the problem persists.
