### ISSUE TITLE
Error: Could not load signature of TensorFlowSharp.Android.NativeBinding:get_InternalPrintFunc due to: 

### ISSUE THREAD

**Issue by lhs21** [Syn-McJ/TFClassify-Unity#34]
unity version:  unity2019.2.0f1   &   unity2019.2.6    (i've tried them all,but none of them worked)
tensorflowsharp version :0.3

i just run your code,but it's wrong even before i bulid the project . i just opened it and loaded
the tensorflowsharp that you provided in the read me.

the whole error is 

Error: Could not load signature of TensorFlowSharp.Android.NativeBinding:get_InternalPrintFunc due to: Could not resolve type with token 01000002 (from typeref, class/assembly Print, ) assembly: type:Print member:(null) signature:<none>
Unloading broken assembly Assets/ML-Agents/Plugins/Android/TensorFlowSharp.Android.dll, this assembly can cause crashes in the runtime

i noticed that you said the second problem can be ignored.  but the fisrt one really bother me a lot 
thankd a lot if sb can tell me about how to fix it .

**Comment by darul360** [comment]
That worked for me on android (build) Unity 2019.1.14 & Unity 2019.2.0f1
1.Go to Assets->ML-Agents->Plugins->Android, click on TensorflowSharp.Android and diselect Editor.
2.Go to Classifier.cs and Detector.cs and change  #if UNITY_ANDROID to #if (UNITY_ANDROID && !UNITY_EDITOR).
3.Select Window > General > Services and create service for this project.
4.On my mac there were some errors during build like `"Microsoft Visual version..."`
make the error bigger or scroll down and you will see errors like : 
`error CS1703: Multiple assemblies with equivalent identity have been imported unity`, go to  Assets->ML-Agents->Plugins->Android and delete dll's that are duplicated.
5.After that build project and all errors should dissappear.

**Comment by Syn-McJ** [comment]
I'm going to close this issue, feel free to reopen if the problem persists.
