### ISSUE TITLE
TypeLoadException: Could not find method due to a type load error

### ISSUE THREAD

**Issue by tomret** [Syn-McJ/TFClassify-Unity#36]
when i play it ,unity show me the error that
 TypeLoadException: Could not find method due to a type load error
PhoneCamera.LoadDetector () (at Assets/Scripts/PhoneCamera.cs:159)
PhoneCamera.LoadWorker () (at Assets/Scripts/PhoneCamera.cs:132)
PhoneCamera.Start () (at Assets/Scripts/PhoneCamera.cs:53) ,what's the problem?

**Comment by ProboticsX** [comment]
@tomret same problem for me... did you find any solution yet? Please tell

**Comment by Syn-McJ** [comment]
I'm guessing InvokeRepeating has troubles finding required method, not sure why. You don't have to use InvokeRepeating to call Detect, but can call it in a while cycle or in Update method. Similar to my new example: https://github.com/Syn-McJ/TFClassify-Unity-Barracuda/blob/master/Assets/Scripts/PhoneCamera.cs#L86
