### ISSUE TITLE
tensorflow 2.0,and training model,does it work?

### ISSUE THREAD

**Issue by HolyShitKillingMachine** [Syn-McJ/TFClassify-Unity#39]
I'm a unity developer,wanna use tensorflow.
so i found this.and wanna use tensorflow 2.0 for unity
i wonder if it works with tensorflow 2.0 model training.

I see you upgrade your project last month.
so i wonder if you can support tensorflow 2.0

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine,

Unfortunately no, I don't think it's possible since TensorflowSharp plugin only supports earlier versions of TensorFlow. Unless tf2 has some kind of backward compatibility model freezing or converting which I don't think it does. Unity won't be updating the plugin since they have their own inference engine now. 

So another option would be to train with TensorFlow 2, freeze the model and try to convert it to Barracuda format to use with Unity's new Barracuda inference engine. See my other example: https://github.com/Syn-McJ/TFClassify-Unity-Barracuda

**Comment by HolyShitKillingMachine** [comment]
> @HolyShitKillingMachine,
> 
> Unfortunately no, I don't think it's possible since TensorflowSharp plugin only supports earlier versions of TensorFlow. Unless tf2 has some kind of backward compatibility model freezing or converting which I don't think it does. Unity won't be updating the plugin since they have their own inference engine now.
> 
> So another option would be to train with TensorFlow 2, freeze the model and try to convert it to Barracuda format to use with Unity's new Barracuda inference engine. See my other example: https://github.com/Syn-McJ/TFClassify-Unity-Barracuda

So ,it is too difficult for the fresh tensorflow user to use the object-detection

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine 
It's not that difficult, but if you a new user it might be a challenge, yes.

**Comment by HolyShitKillingMachine** [comment]
@Syn-McJ I am using the project ,and using 1.7.1 tensorflow ,export my pb file,change to bytes.use the classify,but came with the error in windows,
![image](https://user-images.githubusercontent.com/4986326/76294560-03942380-62ee-11ea-8425-9466ba991874.png)
After exporting it to a apk,it does not work

**Comment by HolyShitKillingMachine** [comment]
@Syn-McJ 
the png has failed to upload
Error is this!

TFException: Invalid GraphDef
TensorFlow.TFStatus.CheckMaybeRaise (TensorFlow.TFStatus incomingStatus, System.Boolean last) (at <1fe2de69842a4a4ba15256b83cca05f3>:0)
TensorFlow.TFGraph.Import (TensorFlow.TFBuffer graphDef, TensorFlow.TFImportGraphDefOptions options, TensorFlow.TFStatus status) (at <1fe2de69842a4a4ba15256b83cca05f3>:0)
TensorFlow.TFGraph.Import (System.Byte[] buffer, TensorFlow.TFImportGraphDefOptions options, TensorFlow.TFStatus status) (at <1fe2de69842a4a4ba15256b83cca05f3>:0)
TensorFlow.TFGraph.Import (System.Byte[] buffer, System.String prefix, TensorFlow.TFStatus status) (at <1fe2de69842a4a4ba15256b83cca05f3>:0)
TFClassify.Classifier..ctor (System.Byte[] model, System.String[] labels, System.Int32 inputSize) (at Assets/Scripts/Classifier.cs:31)
PhoneCamera.LoadClassifier () (at Assets/Scripts/PhoneCamera.cs:170)
PhoneCamera.LoadWorker () (at Assets/Scripts/PhoneCamera.cs:163)
PhoneCamera.Start () (at Assets/Scripts/PhoneCamera.cs:59)

**Comment by HolyShitKillingMachine** [comment]
i have checked that ,ML Agent seems not to work with 1.7.1
https://github.com/Unity-Technologies/ml-agents/issues/609

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine 
If you trained your model with tf 1.7.1, you will need to install 0.4 version of the plugin:
https://s3.amazonaws.com/unity-ml-agents/0.4/TFSharpPlugin.unitypackage

**Comment by HolyShitKillingMachine** [comment]
@Syn-McJ i have tested it with 0.4 version tf1.7.1,and it works bad.
came out this problem.
shows the Invalid GraphDef problem

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine 
If you send me your model, I can take a look at it and check why it doesn't work.

**Comment by HolyShitKillingMachine** [comment]
@Syn-McJ OK，i hava change the pb to bytes,and it can recognize apple and banana!

**Comment by HolyShitKillingMachine** [comment]
it is too big for upload!
can you give me your email,so that i can send to you @Syn-McJ

**Comment by HolyShitKillingMachine** [comment]
@Syn-McJ Now,i am using the Barracuda sample,hope it works.
I am using a android projector,and wanna detect  and show the recipe about the food,and the projecter is used in smart home.

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine,
SSD model won't work with barracuda, you'll need a YOLO model for that.
You can send me your model on syn-mcj@mail.ru

**Comment by tomret** [comment]
could i use tensorflow1.14.0 to train my model to use in this project ? thank U

**Comment by Syn-McJ** [comment]
@tomret,
No, you can use tf 1.4 with the 0.3 version of plugin or 1.7.1 with the 0.4 version of the plugin.
If you need to use newer tensorflow versions, you might try to convert your model to Barracuda format and check my other example: https://github.com/Syn-McJ/TFClassify-Unity-Barracuda

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine 
Your model seems to be fine, you're using the wrong scene. Classify is for image classification, Detect is for object detection.
