### ISSUE TITLE
How to export or convert graph.pb to use with Unity

### ISSUE THREAD

**Issue by HappyModeOn** [Syn-McJ/TFClassify-Unity#4]
I looking for the way to export or convert graph.pb that I made a from outside unity to use in Unity as .bytes like you use in you project

sorry this is not your project issue but I think maybe you can light me out?

**Comment by Syn-McJ** [comment]
The way I export .pb graphs into Unity as .bytes is simply by renaming the file extension from .pb to .bytes. The code using this model will just read the file as byte array.

**Comment by HappyModeOn** [comment]
I try it and it freeze maybe I will try it again anyway thanks for replied

**Comment by Syn-McJ** [comment]
Ok, if that answers your question, I'll close this issue then.
