### ISSUE TITLE
do not know how to set classifyImageSize, IMAGE_MEAN, IMAGE_STD, INPUT_NAME and OUTPUT_NAME

### ISSUE THREAD

**Issue by HolyShitKillingMachine** [Syn-McJ/TFClassify-Unity#41]
classifyimagesize are the input size of the image ,pixel
Image_MEAN and Image_STD are both tensor handle factor
INPUT NAME and OUTPUT NAME are have never been used in the project.
I donot know how they are connected with each other,and how to set it.
After import 0.4 TF Sharp,export pd file with tensorflow 1.7.1 with faster_rcnn_inception_v2_pets model.
i have changed the bytes and import it ,edit my labels file.but it came out with that problem when running
![image](https://user-images.githubusercontent.com/4986326/76586052-ad57f800-651a-11ea-9244-966289d905ba.png)

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine
First of all, you're using the Classify scene which is for image classification, not object detection. 

Second, even in the Detect scene, you cannot just use any model architecture interchangeably. This Detect sample works with SSD-Mobilenet architecture and if you want to use RCNN instead, you'll need to replace the code that feeds input into the network and retrieves and processes the output.

Detect sample in my other repo works with YOLO, so you won't be able yo use RCNN there without code modification as well.

**Comment by HolyShitKillingMachine** [comment]
@Syn-McJ all this you have not mentioned before.So you mean,DETECT with SSD_MOBILENET

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine,
Yes, detect scene and ssd-mobilenet model.
