### ISSUE TITLE
Error：Index was outside of the bounds of the array

### ISSUE THREAD

**Issue by HolyShitKillingMachine** [Syn-McJ/TFClassify-Unity#42]
I have used ssd-mobilenet-v1 to train my pb file,and edit the label txt file.
And run the detect demo,it cames out that error.
I have checked the detail!
![image](https://user-images.githubusercontent.com/4986326/76843948-86c9f200-6877-11ea-8058-0d751f89a4cb.png)
![image](https://user-images.githubusercontent.com/4986326/76843989-9b0def00-6877-11ea-9374-389bf5e85193.png)
![image](https://user-images.githubusercontent.com/4986326/76844023-ac56fb80-6877-11ea-92ed-97469b7bf3b8.png)
I only got 5 objects to detect,and the valve is 5,so the label =  this.labels[5],so then out of the index.
I do not know how to fix this,cause the classes's valve came from the DetectAsync.
would you help?

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine,
Send me your model and labels, I'll check.

**Comment by HolyShitKillingMachine** [comment]
@Syn-McJ I have sent it to your email.syn-mcj@mail.ru

**Comment by HolyShitKillingMachine** [comment]
@Syn-McJ how about the pb file and the label files,are they ok for use?

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine, did you check your model with python before using it in my example? 

I'm checking it now and it doesn't seem to work. Additionally, I can see it producing labels with index 5 while you have only 5 labels which means max index is 4, therefore it causes out of range exception.

This repository isn't meant for teaching how to train tensorflow models, for this please refer to the documentation at tensorflow.org.

Please refrain from creating new tickets before you made sure that your model works well with python inference code.
