### ISSUE TITLE
does classify works fine?

### ISSUE THREAD

**Issue by HolyShitKillingMachine** [Syn-McJ/TFClassify-Unity#43]
I am also using the inception v1 to train my model.
but it seems not work very well.
![image](https://user-images.githubusercontent.com/4986326/77047833-67aa9c00-6a00-11ea-8141-b8752f4d84c5.png)

**Comment by HolyShitKillingMachine** [comment]
![image](https://user-images.githubusercontent.com/4986326/77047954-99bbfe00-6a00-11ea-8357-033f2c3275a5.png)
by the way,you haven't answered my email yet,have you got time for this?
thanks a lot.

**Comment by Syn-McJ** [comment]
Yes, this example works fine as you can see with the model provided with the repository, and it has been tested with other models as well. The issue must be with your model specifically.

Please refrain from creating new tickets before you made sure that your model works well with python inference code.
