### ISSUE TITLE
How can I run this app with my own classification network?

### ISSUE THREAD

**Issue by hojoonson** [Syn-McJ/TFClassify-Unity#7]
Hi.
I want to use your excellent unity-tensorflow classification app with my own classification network.

I simply make .pb file of my network and rename the file type with .byte
However, it doesn't work.

My question is did you test this application with another .pb file??
I think, only the "tensorflow_inception_graph.pb" from tensorflow repository works.

**Comment by Syn-McJ** [comment]
Hi, yes, I did check it with some other MobileNet models as well. There might be several reasons for you to have problems for your model, please check these issues to see if solutions can be applied to your case:

https://github.com/Syn-McJ/TFClassify-Unity/issues/5
https://github.com/Syn-McJ/TFClassify-Unity/issues/6

Let me know if it still doesn't work, I'll be glad to help.

**Comment by hojoonson** [comment]
Thanks a lot. I will try :)

**Comment by hojoonson** [comment]
Thank you and I fixed my previous error.
But now I have a new error like this.
I think it is because of size of input image.
Any recommendation please ? :)

IndexOutOfRangeException: Index was outside the bounds of the array.
TFClassify.Classifier.TransformInput (UnityEngine.Color32[] pic, System.Int32 width, System.Int32 height) (at Assets/Scripts/Classifier.cs:86)
TFClassify.Classifier+<ClassifyAsync>c__AnonStorey0.<>m__0 () (at Assets/Scripts/Classifier.cs:43)
System.Threading.Tasks.Task`1[TResult].InnerInvoke () (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.Threading.Tasks.Task.Execute () (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
PhoneCamera+<TFDetect>c__async0.MoveNext () (at Assets/Scripts/PhoneCamera.cs:112)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:92)
UnityEngine.UnitySynchronizationContext.Exec () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:53)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:74)

**Comment by Syn-McJ** [comment]
Indeed, it seems like a mismatch between image size you actually have and image size you're specifying. Make sure that length of `Color32[] pic` array in the `Classifier.TransformInput` method equals `width * height`.

The size of an image that tensor expects is set in the `INPUT_SIZE` variable. So if it's set to 224, then make sure your image is cropped and rescaled to this exact size (224*224) before feeding it to the classifier.

If you have troubles fixing it, then I'll need your model and a picture example to check it myself.

**Comment by Syn-McJ** [comment]
Is your problem resolved? I will close this issue if so.

**Comment by hojoonson** [comment]
Yes I resolve my problem!! thanks a lot

2018년 4월 29일 (일) 오전 12:45, Andrey Ashikhmin <notifications@github.com>님이 작성:
