### ISSUE TITLE
App stop after 2 minutes

### ISSUE THREAD

**Issue by ngahchi** [Syn-McJ/TFClassify-Unity#8]
I have tried to build and run both the classify and detect scene, both work, but after 2 minutes, the app will stop / crashed with the following error message:

W/Adreno-GSL: <sharedmem_gpuobj_alloc:2337>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL: <gsl_memory_alloc_pure:2203>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x259f6d0 in tid 6458 (UnityGfxDeviceW)

My testing phone is Samsung Note 8, Android 8.0.0
Thanks a lot!

**Comment by Syn-McJ** [comment]
Probably a memory leak. I will check, thanks for reporting.

**Comment by Syn-McJ** [comment]
I added some `Dispose()` for tensorflow objects and `Destroy()` for textures, should be fine now. Tested on Galaxy 8, memory was just under 100Mb for both scenes.
