### ISSUE TITLE
Will this framework works in iOS

### ISSUE THREAD

**Issue by Sharathmk99** [Syn-McJ/TFClassify-Unity#9]
Hi All,

I wanted to use Object detection API with Unity3D and support both Android and iOS platform.
I understood it works in Android, what about iOS?

**Comment by Syn-McJ** [comment]
Hi @Sharathmk99,
Unfortunately, I don't have an iOS device to test it, but from first glance I don't see why it wouldn't work. If you can try it and provide feedback that'd be great.

**Comment by Syn-McJ** [comment]
I'm gonna close this issue for now, feel free to reopen if you have any specific problem with deploying on iOS.
